### ISSUE TITLE
Offline login doesn´t work on laptops

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#246]
How to repeat
- install a latop
- login with network
- reboot
- try to login without network connection

**Comment by juhaerk** [comment]
This should work now. The problem was apparently related to sssd somehow, but I got tired of trying to figure it out (the way we currently use sssd is somewhat unorthodox, I think). So I ended up rewriting the authentication, sssd is no longer used. The offline logins should work on laptops now, closing.
