### ISSUE TITLE
Pinta easily crashes after a few minutes of use

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#285]

**Comment by jarmopi** [comment]
Seems to be caused by high CPU usage during certain operations (creating colour gradients, for example), which trigger a SIGPWR signal. If Pinta is executed inside a debugger (like gdb), you can just `continue` until the program execution resumes. A patch exists, but we'll probably have to compile a new version by ourselves.

**Comment by asokero** [comment]
Pinta is not available anymore in puavo-os nor in Debian. Closing.
