### ISSUE TITLE
Sound devices not usable when user belongs to many schools

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#319]
Same as the ticket for the current production system. https://github.com/opinsys/puavo/issues/323

**Comment by juhaerk** [comment]
This issue is because puavo might have user group-memberships in an inconsistent state: user has a primary group that he/she does not belong to (?).  Meaning that puavo-rest session has information, that user has a particular gid as a primary group, but nothing is known about that group... This must be fixed in Puavo and should not be worked around on bootservers/devices.

**Comment by juhaerk** [comment]
I accidentally closed this... even though this does not belong to "puavo-os", the issue still exists.
