### ISSUE TITLE
Add mime type for smartboard .notebook files

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#336]
Souble clicking .notebook file should open the file on Smart notebook software.

**Comment by juhaerk** [comment]
Fixed in commits 9efb62c69408fe57e601420ffc2d04f63893d9f7, 83503f765bca8d6d50835d4c5b0a30bc6232fa91, 41d004990606cfebdf9a023190d6af8c8e6d4373, 0db4369c0323d56cd95bf2271ed177c2673aed24 and 8d05f3e7a0ff3dfa00bd9e885b940fc637cea9fa. Note that there are likely some similar mime-type issues with other puavo-pkg packages, depending on some factors, because "update-mime-database" may not be run at the right time.
