### ISSUE TITLE
Automatic cleanup for laptop home folders

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#365]
There is need for deleting home folders on shared laptops. The need for this comes from:
- Laptops have small hard drive/home partition and therefore the device cannot be used anymore when several different users login and free space runs out.
- Unused home folders and folders that do not have the primary user account any more should automatically be removed.

The cleaning process should be able to be activated/deactivated with puavo-conf. Some rough ideas for the clean up process:
- It should alvays be activated if free space on home is less that 1GB
- Always remove user accounts that have not been used withing one year and that do not have a user account anymore.
- Remove the oldest home folder by modify time. 
- If size of the home partition is small (causes the clean up to happen often), a message could be shown to the user, telling that "Due to low mass storage space on this laptop, locally saved files might be often automatically cleaned up/deleted".

**Comment by juhaerk** [comment]
Partially implemented in 583914389cc1ab5bd147867129436f68a55d9269, ba277339e220b6c9f31a41b41d932294668594b8 and 30595cb2de9f118283084da8438b107c1b6fea01.

Removing home directories from removed users is problematic, because currently a device/user has no permissions to know, which users have been deleted from Puavo, because of access restrictions.

**Comment by juhaerk** [comment]
My previous comment was wrong, a device *has* enough permissions to lookup a list of users in an organisation.
