### ISSUE TITLE
Lego EV3 robot with fw 1.10e cannot be mounted as usb drive

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#452]
The latest firmware upgrade from Lego should make it possible to mount the EV3 brick as a usb device. This seems to work on the Ubuntu Trusty based system and with legacy kernel on Strech device images.

If this would work it would be possible to use the Microsoft Makecode service to program the lego robots.

https://makecode.mindstorms.com/

**Comment by asokero** [comment]
https://github.com/microsoft/pxt-ev3/issues/980

**Comment by asokero** [comment]
https://github.com/c4ev3/ev3duder/issues/31

**Comment by Mazhoon** [comment]
Fixed in bullseye with https://github.com/puavo-org/puavo-os/commit/16b7c94935cba56820fc2f82a378983772ff5534 .
As the filesystem presented by the device is virtual, we can safely ignore any errors and keep using the drive without remounting read-only. The required setting is only available in recent udisks2 versions, and this fix is therefore not applicable in buster-based systems.
