### ISSUE TITLE
Some PNG images are not shown 

### ISSUE THREAD

**Issue by ralf-krause** [puavo-org/puavo-os#459]
Hi, 
I found that some screenshots from my Android tablet are not shown in the "Eye of Gnome" picture view. This picture view is the default app to show png images. The same problem is with MyPaint but I can open the screenshots with Firefox or Chromium browser, also with GIMP and Shotwell.

You will find a screenshot for an example in the attachment of this issue. This example does not open with "Eye of Gnome" and MyPaint.

Best regards, Ralf

**Comment by ralf-krause** [comment]
![Screenshot_2019-03-10-15-19-47](https://user-images.githubusercontent.com/27956839/54089665-bd6b5380-436b-11e9-870b-cb12d0a35a2f.png)

**Comment by asokero** [comment]
It seems like the problem is caused by the incorrect file suffix. If I investigate the file it actually seems to be a jpeg file not png, although the .png suffix claims something else. 

`
$ file eog-png-issue.png 
eog-png-issue.png: JPEG image data, Exif standard: [TIFF image data, big-endian, direntries=3, orientation=[*0*], software=Aviary for Android 4.8.4], baseline, precision 8, 1536x2048, frames 3
`
So could this be a bug in the screenshot app on the tablet?

It seems that web browsers ignore the suffix and investigate the actual file type. Then again eog and mypaint trust the incorrent suffix and are unable to open the file.

So changing the suffix to .jpg solves the issue.
