### ISSUE TITLE
Add support for Papercut

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#461]
Papercut provides a way to bring securu printing queues to normal network printers.

Could this be made with...
- puavo-pkg?
- separete Papercut-box/device?
- virtual machine on bootserver?

**Comment by juhaerk** [comment]
A preliminary version of this (as a puavo-pkg) has been done.  Unfortunately it is in a private repository, because there are not public urls (without registration) for the software, thus it would not work out-of-the-box anyway.

Maybe we should considering putting some of the puavo-pkgs to public repository anyway... (currently the policy is to create private puavo-pkgs for software, which are not publicly available on the internet).

Closing, because this is moving into testing phase (despite the lack of public commits :-( )
