### ISSUE TITLE
Update TI CAS to 5.x release

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#510]

**Comment by juhaerk** [comment]
Version 5.1.3.73 works with Wine version 5.11, including license activation in case the C-drive serial number has been set.

**Comment by juhaerk** [comment]
To me more exact, there is still (I think) a showstopper with Wine version 5.11. When license needs to activated, the fonts are barely readable and maybe are not on some screens. I got through it mostly because I know what the texts say and the buttons do, but we can not expect others to know that.

I have no clue how this could be solved. I have tried many things, different Wine versions (5.0 is still broken btw), user interface theming, installing Gecko (that is not packaged by the upstream Wine), and other things.
