### ISSUE TITLE
Starting Puavo OS Command Shell (pxe boot) takes long

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#519]

**Comment by juhaerk** [comment]
The culprit was virtualbox that compiled its kernel modules on each boot. The problem was on all hosts, but was most visible when starting up Puavo OS Console, because that would wait until the module build was complete. Fixed in https://github.com/puavo-org/puavo-os/commit/c9d68ba2534f7d0008a4478d9a1fa1664ebf5b84 and https://github.com/puavo-org/puavo-os/commit/ee35dec3746ec362cf04e0cd72d63b35bfef0550 though I have not yet tested Virtualbox yet after this change.
