### ISSUE TITLE
Send bootserver hwinfo to puavo

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#529]

**Comment by juhaerk** [comment]
Current situation as I can see it: bootserver try to send it, using /v3/devices/:hostname/sysinfo. But does not succeed, because bootservers are not devices according to puavo-rest logic (Device.by_hostname!(hostname) does not find it). LDAP-side is okay.

There might be a quick fix, however the odd server/device-split might need refactoring, because similar issues might come up later.

**Comment by asokero** [comment]
Done https://github.com/puavo-org/puavo-os/commit/20393582f0cb4b6e2a70d635573ec024ecc57049
