### ISSUE TITLE
Installing puavo on a hd with preexisting puavo installation allways fails at first attempt.

### ISSUE THREAD

**Issue by basilstotz** [puavo-org/puavo-os#540]
The second attempt woks nicely.  Not a big problem, but a little bit ugly (specially for presentations)

**Comment by juhaerk** [comment]
Thanks for the bug report. This is a known issue and has been fixed in Buster: https://github.com/puavo-org/puavo-os/commit/ba3820b4daa279c61174873e5adbc5c4cde30d88 (I believe, mostly, there may be some edge cases left).

I am not sure if we are going to backport the fixes to Stretch. The relevant code has other changes such as UEFI support and it is no longer apparent which commits should be merged to Stretch, especially as the installation code in Buster has not been tested much yet.

Closing in any case... Buster should be ready for production in summer/autumn this year, testers are welcome ;-)
