### ISSUE TITLE
Can't use appImage software with Puavo Buster

### ISSUE THREAD

**Issue by ralf-krause** [puavo-org/puavo-os#553]
Hi,
I installed the beta release 02014 for Puavo OS with Buster. Now I can't start the Balena Etcher appImage any more. I think that Puavo should come with the AppImageLauncher.
Best regards from Germany, Ralf

**Comment by asokero** [comment]
This is a know problem and caused by the changes in the upstream Gnome desktop environment. It affects executing any binary, desktop and script files via file manager. https://gitlab.gnome.org/GNOME/nautilus/commit/3a22ed5b8e3bbc1c59ff3069ee79755168754916

The change was made to Gnome to achieve better security. We will see what would be needed to make it possible again with Buster.

**Comment by asokero** [comment]
There was problem with some AppImages that were based on Electron. Executing these was prevented by kernel security settings. This is not a problem anymore. https://github.com/puavo-org/puavo-os/commit/f06ea7c4126bfa3bdf9fa792cccd0aa4ad180010
