### ISSUE TITLE
Hide/Show desktop button at desktop bottom panel

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#622]
The old gnome extension does not work anymore so we might want to find a replacement. Dash to panel might also include this functionality, but will need some testing/settings.

**Comment by sarrchri** [comment]
Fixed as of https://github.com/puavo-org/puavo-os/commit/d5d5994b41b1d063628f76563a1ebcd9422622a7.

The button funcionality itself was pretty straightforward to fix. However, the extension also had a Preferences page, which apparently has not worked since Bullseye (this page was located in Gnome Extensions menu).

After a brief discussion with @juhaerk regarding how to proceed with this, we came to the conclusion that we don't need the Preferences page and can just drop said functionality whole.
