### ISSUE TITLE
Gnome appearance settings in Bookworm

### ISSUE THREAD

**Issue by asokero** [puavo-org/puavo-os#623]
The new gnome control center also has a new appearance settings. We would need to merge our own (bullseye) appearance settings (such as cursor and ui theme selection, darkmode etc.) with the native Gnome settings.

**Comment by juhaerk** [comment]
I took a look at this. Merging to the background panel (which has its own light/dark theme chooser) looks tricky and does take some effort. Keeping it separate would be easier, but not as nice I think. It does not build currently, because it should use GTK4 and tries to use a method that is only available on GTK3.

Now that the gnome control center has a light/dark theme chooser, I wonder do we really need to provide this kind of tweakability to UI?

**Comment by juhaerk** [comment]
The "gnome-tweaks" utility already provides a UI for some of the settings we have had in our "appearance"-panel. One alternative would be allow access to this utility. In case there is a concern that it might allow too much tweaking, we could look into mechanisms to restrict its applicability. It's written in Python and looks like it is easier to customize than Gnome Control Center.

**Comment by asokero** [comment]
There is a new more specific issue about this case  https://github.com/puavo-org/puavo-os/issues/669. Closing this one.
