### ISSUE TITLE
Bluetooth does not work in Bookworm

### ISSUE THREAD

**Issue by ralf-krause** [puavo-org/puavo-os#635]
Dear developers,
I found that my Puavo device md-lap-3011.magdeburg.opinsys.fi with opinsys-os-opinsys-bookworm-2023-10-04-121631-amd64 can't connect via Bluetooth. 

My device uses two images ... opinsys-os-opinsys-bookworm-2023-10-04-121631-amd64 and opinsys-os-opinsys-bullseye-2023-10-04-074857-amd64. In Bullseye everything is okay but Bookworm starts without Bluetooth and I can't switch Bluetooth on in the system settings. Yes, I have admin right for my device.

Without Bluetooth a lot of programs do not work properly. I can't use https://spike.legoeducation.com for programming Lego robots. I can't use Scratch and Scratch Link to connect to my micro:bit. KDE connect does not connect to my iPhone and my iPad ... all three devices are in the same wifi network but the Puavo device does not have Bluetooth.

Ralf

**Comment by sarrchri** [comment]
Hi,

I just tested this with a HP EliteBook 820 G3, equipped with Intel Wireless 8260 WiFi/BT-combo card (same as on your device), running on 2023-11-03 bookworm image and I was not able to reproduce this.

I have also been running our bookworm images on my work laptop (HP EliteBook 830 G5) since the first development image, and after the one that fixed Bluetooth connectivity, I've not had any issues using Bluetooth. Of course, that doesn't mean there can't be something wrong with the image, the kernel or something like that, but usually in these situations the device tends to be at fault.

I see your device has a BIOS version 1.52, while the newest is version 1.60. I would advise to update the BIOS just in case, as sometimes it fixes weird issues. Please report back after you've updated the BIOS and tested Bluetooth again on the latest image. :)

The device BIOS can be updated from BIOS itself with a network cable and charger connected, or you can open terminal on the device, log in as root with `sudo su` and run `puavo-bios-config` and select the option `Flash Latest BIOS (HP)`, follow the instructions on screen and reboot the device after the tool says it's finished.

**Comment by ralf-krause** [comment]
Hey Christian,
I just flashed the BIOS of my device md-lap-3011 up to 1.60. It’s very easy with the command puavo-bios-config. 

And I also have the current Bookworm image opinsys-os-opinsys-bookworm-2023-11-03-091807-amd64. Yes, now bluetooth is activated by default at the system start. And yes, I can connect to my Lego hubs with the web app https://spike.legoeducation.com. Great! It works!

Does this mean that all Puavo devices in Magdeburg need an BIOS update before they could run any Bookworm image together with Bluetooth? Last week I also had some problems with KDE Connect on my test device md-lap-3011 but I could not get an idea for this.

Best regards,
Ralf

**Comment by sarrchri** [comment]
Hi Ralf,

I'm glad to hear the problem was solved on your device.

Based on just one device, we don't know if it is a *requirement* to update the BIOS prior to Bookworm. But in general, a device BIOS is something that is good to be kept reasonably up-to-date. BIOS updates usually include CVE fixes and such and they tend to also fix random issues.

I'm not saying you should start a BIOS update marathon on every device, but I guess this is something that should be tested on a couple more identical devices to be sure. If there are no problems on other HP EliteBook 820 G3 with BIOS 1.52 or such on Bookworm, then the BIOS update should not be a requirement for Bookworm.

Of course, it can't really hurt to update the device BIOSes in time, but when there's a lot of devices it's going to be quite a job to update them all. So moderation in everything.
A device BIOS can be updated when convenient to do so, like if someone from the school IT support has to handle / troubleshoot the device, let's say due to booting issues as an example. A simple power reset might end up fixing it, but that's also a good opportunity to also update the device BIOS while they're at it. :)

**Comment by ralf-krause** [comment]
Hey Christian,
I tested my Lego Spike Prime and Lego Spike Essential with Bluetooth and the WebApp https://spike.legoeducation.com ... it works fine with Bookworm after I updated the BIOS from 1.51 to 1.60 for my test devices HP EliteBook 820 G3 and 840 G3. You will find my test devices here https://magdeburg.opinsys.fi/devices/502444/devices

Now I tested a fourth device HP EliteBook 820 G3 with BIOS 1.53 and this device https://magdeburg.opinsys.fi/devices/502444/devices/557083 works also fine with Bluetooth and Bookworm. 

There is another issue https://github.com/puavo-org/puavo-os/issues/636 with Bookworm and bluetooth. It could be that the reasons for the Scratch Link are some Bookworm changes with Bluetooth, too.

Ralf
